openapi: 3.0.3
info:
  title: TodoList
  description: TodoList
  version: 1.0.0
servers:
  - url: 'http://127.0.0.1:88'
paths:
  /api/user/login:
    post:
      summary: User Login
      description: Authenticate a user by email and password.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: User's email address.
                  example: admin@example.com
                password:
                  type: string
                  description: User's password.
                  example: password
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Login successful
                  token:
                    type: string
                    example: JWT_token_here
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid credentials
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: An error occurred on the server
  /api/user/data:
    get:
      summary: Get User Data
      description: Retrieve user data for the currently authenticated user.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: User data retrieved successfully
          content:
            application/json:
              schema:
                type: object
  /api/user/logout:
    post:
      summary: User Logout
      description: Log out the currently authenticated user.
      security:
        - bearerAuth: []
      responses:
        '204':
          description: Logout successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logout successful
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unauthorized access
components:
  securitySchemes:
    bearerAuth:
      type: http
      description: JWT Authorization header using the Bearer scheme
      scheme: bearer
      bearerFormat: JWT


